# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
